catalogo/config/routes.rb
Rails.application.routes.draw do
  resources :proveedores
  resources :productos_detalles
  resources :productos
  resources :marcas
  resources :modelos
  resources :categorias
  get 'home/index'

   root 'home#index'

end

catalogo/app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :marca
  belongs_to :modelo
  belongs_to :categoria
  has_many :productos_detalles
end

catalogo/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :codigo, :descripcion, :precio_venta, :marca_id, :modelo_id, :categoria_id, :imagen)
    end
end

catalogo/app/helpers/productos_helper.rb
module ProductosHelper
end

catalogo/app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precio_venta %><br>
    <%= f.text_field :precio_venta %>
  </div>
  <div class="field">
    <%= f.label :marca_id %><br>
    <%= f.text_field :marca_id %>
  </div>
  <div class="field">
    <%= f.label :modelo_id %><br>
    <%= f.text_field :modelo_id %>
  </div>
  <div class="field">
    <%= f.label :categoria_id %><br>
    <%= f.text_field :categoria_id %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.text_field :imagen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

catalogo/app/views/productos/edit.html.erb
<h1>Editando Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

catalogo/app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Descripcion</th>
      <th>Precio venta</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Categoria</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.codigo %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio_venta %></td>
        <td><%= producto.marca %></td>
        <td><%= producto.modelo %></td>
        <td><%= producto.categoria %></td>
        <td><%= producto.imagen %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

catalogo/app/views/productos/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

catalogo/app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @producto.codigo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Precio venta:</strong>
  <%= @producto.precio_venta %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @producto.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @producto.modelo %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @producto.categoria %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @producto.imagen %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>