catalogo/config/routes.rb
Rails.application.routes.draw do
  resources :proveedores
  resources :productos_detalles
  resources :productos
  resources :marcas
  resources :modelos
  resources :categorias
  get 'home/index'

   root 'home#index'

end

catalogo/app/models/categoria.rb
class Categoria < ActiveRecord::Base
	has_many :productos
end

catalogo/app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all
    @categoria = Categoria.new
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria was successfully created.' }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: 'Categoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria.destroy
    respond_to do |format|
      format.html { redirect_to categorias_url, notice: 'Categoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_params
      params.require(:categoria).permit(:descripcion)
    end
end

catalogo/app/helpers/categorias_helper.rb
module CategoriasHelper
end

catalogo/app/views/categorias/_form.html.erb
<%= form_for(@categoria) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-lg-4">
      <div class="field">
        <%= f.label :categoria %><br>
        <%= f.text_field :descripcion, autofocus: true , class: 'form-control' %>
      </div>
    </div>
  </div>
 <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-offset-10 col-md-3 col-lg-3">
      <div class="actions">
       <%= button_tag "Cancelar", type: :reset , id: 'btn_cancelar',:class => 'btn btn-reset'%>
        <% if controller.action_name == 'new' or controller.action_name == 'index' %>
          <%= f.submit "Agregar", :class => 'btn btn-primary'%>
        <% elsif controller.action_name == 'edit' %>
          <%= f.submit "Actualizar", :class => 'btn btn-primary'%>
        <% end %>
      </div>
    </div>
  </div>

<% end %>
</br>

<div class="separador"></div>

catalogo/app/views/categorias/edit.html.erb
<h1>Editing Categoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria %> |
<%= link_to 'Back', categorias_path %>

catalogo/app/views/categorias/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 id="titulo_firmante"> Categorias 
      <button type="button" class="btn btn-info btn-outline btn-circle" id="btn1">
        <span class="glyphicon glyphicon-chevron-up" id="gbtn1"></span>
      </button>
  </h1>

    <div id="form-toggle">
      <%= render 'form' %>
    </div>

  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Categoria</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categorias.each do |categoria| %>
        <tr>
          <td><%= categoria.descripcion %></td>
          <td><%= link_to 'Show', categoria %></td>
          <td><%= link_to 'Edit', edit_categoria_path(categoria) %></td>
          <td><%= link_to 'Destroy', categoria, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

catalogo/app/views/categorias/new.html.erb
<h1>New Categoria</h1>

<%= render 'form' %>

<%= link_to 'Back', categorias_path %>

catalogo/app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @categoria.descripcion %>
</p>

<%= link_to 'Edit', edit_categoria_path(@categoria) %> |
<%= link_to 'Back', categorias_path %>