catalogo/config/routes.rb
Rails.application.routes.draw do
  resources :proveedores
  resources :productos_detalles
  resources :productos
  resources :marcas
  resources :modelos
  resources :categorias
  get 'home/index'

   root 'home#index'

end

catalogo/app/controllers/productos_detalles_controller.rb
class ProductosDetallesController < ApplicationController
  before_action :set_producto_detalle, only: [:show, :edit, :update, :destroy]

  # GET /productos_detalles
  # GET /productos_detalles.json
  def index
    @productos_detalles = ProductoDetalle.all
  end

  # GET /productos_detalles/1
  # GET /productos_detalles/1.json
  def show
  end

  # GET /productos_detalles/new
  def new
    @producto_detalle = ProductoDetalle.new
  end

  # GET /productos_detalles/1/edit
  def edit
  end

  # POST /productos_detalles
  # POST /productos_detalles.json
  def create
    @producto_detalle = ProductoDetalle.new(producto_detalle_params)

    respond_to do |format|
      if @producto_detalle.save
        format.html { redirect_to @producto_detalle, notice: 'Producto detalle was successfully created.' }
        format.json { render :show, status: :created, location: @producto_detalle }
      else
        format.html { render :new }
        format.json { render json: @producto_detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos_detalles/1
  # PATCH/PUT /productos_detalles/1.json
  def update
    respond_to do |format|
      if @producto_detalle.update(producto_detalle_params)
        format.html { redirect_to @producto_detalle, notice: 'Producto detalle was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto_detalle }
      else
        format.html { render :edit }
        format.json { render json: @producto_detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos_detalles/1
  # DELETE /productos_detalles/1.json
  def destroy
    @producto_detalle.destroy
    respond_to do |format|
      format.html { redirect_to productos_detalles_url, notice: 'Producto detalle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto_detalle
      @producto_detalle = ProductoDetalle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_detalle_params
      params.require(:producto_detalle).permit(:precio_compra, :fecha_compra, :proveedor_id, :producto_id)
    end
end

catalogo/app/helpers/productos_detalles_helper.rb
module ProductosDetallesHelper
end

catalogo/app/views/productos_detalles/_form.html.erb
<%= form_for(@producto_detalle) do |f| %>
  <% if @producto_detalle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto_detalle.errors.count, "error") %> prohibited this producto_detalle from being saved:</h2>

      <ul>
      <% @producto_detalle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :precio_compra %><br>
    <%= f.text_field :precio_compra %>
  </div>
  <div class="field">
    <%= f.label :fecha_compra %><br>
    <%= f.date_select :fecha_compra %>
  </div>
  <div class="field">
    <%= f.label :proveedor_id %><br>
    <%= f.text_field :proveedor_id %>
  </div>
  <div class="field">
    <%= f.label :producto_id %><br>
    <%= f.text_field :producto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

catalogo/app/views/productos_detalles/edit.html.erb
<h1>Editing Producto Detalle</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto_detalle %> |
<%= link_to 'Back', productos_detalles_path %>

catalogo/app/views/productos_detalles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Productos Detalles</h1>

<table>
  <thead>
    <tr>
      <th>Precio compra</th>
      <th>Fecha compra</th>
      <th>Proveedor</th>
      <th>Producto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos_detalles.each do |producto_detalle| %>
      <tr>
        <td><%= producto_detalle.precio_compra %></td>
        <td><%= producto_detalle.fecha_compra %></td>
        <td><%= producto_detalle.proveedor %></td>
        <td><%= producto_detalle.producto %></td>
        <td><%= link_to 'Show', producto_detalle %></td>
        <td><%= link_to 'Edit', edit_producto_detalle_path(producto_detalle) %></td>
        <td><%= link_to 'Destroy', producto_detalle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto detalle', new_producto_detalle_path %>

catalogo/app/views/productos_detalles/new.html.erb
<h1>New Producto Detalle</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_detalles_path %>

catalogo/app/views/productos_detalles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Precio compra:</strong>
  <%= @producto_detalle.precio_compra %>
</p>

<p>
  <strong>Fecha compra:</strong>
  <%= @producto_detalle.fecha_compra %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @producto_detalle.proveedor %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @producto_detalle.producto %>
</p>

<%= link_to 'Edit', edit_producto_detalle_path(@producto_detalle) %> |
<%= link_to 'Back', productos_detalles_path %>