catalogo/config/routes.rb
Rails.application.routes.draw do
  resources :proveedores
  resources :productos_detalles
  resources :productos
  resources :marcas
  resources :modelos
  resources :categorias
  get 'home/index'

   root 'home#index'

end

catalogo/app/models/modelo.rb
class Modelo < ActiveRecord::Base
	has_many :marcas, dependent: :restrict_with_error
	has_many :productos, dependent: :restrict_with_error

	validates :descripcion,
		:presence => {
			message: 'Este campo es requerido'},
		:length => {
			:maximum => 50,
			:too_long => 'debe tener como maximo %{count} caracteres'}

	def nombre_modelo
    "#{descripcion}"
  	end
end

catalogo/app/controllers/modelos_controller.rb
class ModelosController < ApplicationController
  before_action :set_modelo, only: [:show, :edit, :update, :destroy]

  # GET /modelos
  # GET /modelos.json
  def index
    @modelos = Modelo.all
    @modelo = Modelo.new
  end

  # GET /modelos/1
  # GET /modelos/1.json
  def show
  end

  # GET /modelos/new
  def new
    @modelo = Modelo.new
  end

  # GET /modelos/1/edit
  def edit
  end

  # POST /modelos
  # POST /modelos.json
  def create
    @modelo = Modelo.new(modelo_params)

    respond_to do |format|
      if @modelo.save
        format.html { redirect_to modelos_url }
        format.json { render :show, status: :created, location: @modelo }
      else
        format.html { redirect_to modelos_url}
        format.json { render json: @modelo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modelos/1
  # PATCH/PUT /modelos/1.json
  def update
    respond_to do |format|
      if @modelo.update(modelo_params)
        format.html { redirect_to modelos_url }
        format.json { render :show, status: :ok, location: @modelo }
      else
        format.html { render :edit }
        format.json { render json: @modelo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modelos/1
  # DELETE /modelos/1.json
  def destroy
    respond_to do |format|
      if @modelo.destroy
        format.html { redirect_to modelos_url }
        format.json { head :no_content }
      else
        format.html { redirect_to estados_url, notice: 'No se puede eliminar' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modelo
      @modelo = Modelo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modelo_params
      params.require(:modelo).permit(:descripcion)
    end
end

catalogo/app/helpers/modelos_helper.rb
module ModelosHelper
end

catalogo/app/views/modelos/_form.html.erb
<% remote ||= false %>
<%= form_for @modelo, remote: remote, validate: true do |f| %>

  <div class="row">
    <div class="col-sm-12 col-lg-4">
      <div class="field">
        <%= f.label :modelo %><br>
        <%= f.text_field :descripcion, autofocus: true , :class => 'form-control'%>
      </div>
    </div>
  </div>
   <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-offset-10 col-md-3 col-lg-3">
      <div class="actions">
       <%= button_tag "Cancelar", type: :reset , id: 'btn_cancelar',:class => 'btn btn-reset'%>
        <% if controller.action_name == 'new' or controller.action_name == 'index' %>
          <%= f.submit "Agregar", :class => 'btn btn-primary'%>
        <% elsif controller.action_name == 'edit' %>
          <%= f.submit "Actualizar", :class => 'btn btn-primary'%>
        <% end %>
      </div>
    </div>
  </div>

<% end %>
</br>

<div class="separador"></div>

catalogo/app/views/modelos/edit.html.erb
<h1>Editing Modelo</h1>

<%= render 'form' %>

<%= link_to 'Show', @modelo %> |
<%= link_to 'Back', modelos_path %>

catalogo/app/views/modelos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 id="titulo_firmante"> Modelos 
      <button type="button" class="btn btn-info btn-outline btn-circle" id="btn1">
        <span class="glyphicon glyphicon-chevron-up" id="gbtn1"></span>
      </button>
  </h1>

  <div id="form-toggle">
      <%= render 'form' %>
  </div>

  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Modelos</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @modelos.each do |modelo| %>
        <tr>
          <td><%= modelo.descripcion %></td>
          <td><%= link_to 'Show', modelo %></td>
          <td><%= link_to 'Edit', edit_modelo_path(modelo) %></td>
          <td><%= link_to 'Destroy', modelo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

catalogo/app/views/modelos/new.html.erb
<h1>New Modelo</h1>

<%= render 'form' %>

<%= link_to 'Back', modelos_path %>

catalogo/app/views/modelos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @modelo.descripcion %>
</p>

<%= link_to 'Edit', edit_modelo_path(@modelo) %> |
<%= link_to 'Back', modelos_path %>